from django.conf import settings


class ServerEnum:
    # Response CONSTANTS
    RESPONSE_CONNECTION_ERROR = "CONNECTION_ERROR"
    RESPONSE_SUCCESS = "SUCCESS"
    RESPONSE_DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    RESPONSE_PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    RESPONSE_EMAIL_MISMATCH = "EMAIL_MISMATCH"
    RESPONSE_EMAIL_TAKEN = "EMAIL_TAKEN"
    RESPONSE_PHONE_TAKEN = "PHONE_TAKEN"
    RESPONSE_INVALID_JWT_TOKEN = "INVALID_JWT_TOKEN"
    RESPONSE_INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    RESPONSE_INVALID_PHONE_TOKEN = "INVALID_PHONE_TOKEN"
    RESPONSE_WAIT_CUSTOMER_TRIP_ERROR = "PLEASE WAIT FOR CUSTOMER TO END TRIP"
    RESPONSE_CUSTOMER_ALREADY_COMPLETED_TRIP = "YOUR CUSTOMER ALREADY COMPLETED THE TRIP. YOU CAN NOT CANCEL NOW"
    RESPONSE_UPLOAD_CAR_IMAGES = "PLEASE UPLOAD ALL THE CAR IMAGES"
    RESPONSE_BOOKING_CANCELLED_BEFORE = "THE BOOKING IS CANCELLED BY CUSTOMER BEFORE ACCEPTING"
    RESPONSE_NO_AIRPORT = "NO AIRPORT"
    RESPONSE_VALET_HAS_BOOKING = "VALET HAS BOOKING"
    RESPONSE_DISCOUNT_INVALID = "CODE INVALID"
    RESPONSE_DISCOUNT_LIMIT_CROSS = "CODE ALREADY USED"
    RESPONSE_DISCOUNT_NOT_VALID_AIRPORT = "THIS PROMO IS NOT VALID FOR THIS AIRPORT"
    RESPONSE_DISCOUNT_VALID = "VALID PROMO CODE"
    RESPONSE_DISCOUNT_TAKEN = "DISCOUNT ALREADY TAKEN"
    RESPONSE_DISCOUNT_NOT_VALID_CUSTOMER = "THIS PROMO IS NOT VALID FOR YOU"
    RESPONSE_DISCOUNT_NOT_VALID_AMOUNT = "INVALID PROMO CODE, CODE CANNOT HAVE 100% DISCOUNT"

    # SignIn Type
    SIGNIN_GOOGLE = "GOOGLE"
    SIGNIN_PHONE = "PHONE"
    SIGNIN_EMAIL_PASS = "EMAIL_PASS"
    SIGNIN_APPLE = "APPLE"

    # User Type
    USER_SUPER_ADMIN = "SUPER_ADMIN"
    USER_ADMIN = "ADMIN"
    USER_CUSTOMER = "CUSTOMER"
    USER_VALET = "VALET"
    USER_GUEST = "GUEST"

    # App Type
    APP_SUPER_ADMIN = "SUPER_ADMIN"
    APP_ADMIN = "ADMIN"
    APP_GUEST = "GUEST"
    APP_CUSTOMER = "CUSTOMER"
    APP_VALET = "VALET"

    # Update Registration Type
    PROFILE_USER_DETAILS_UPDATE = "PROFILE_USER_DETAILS_UPDATE"
    PROFILE_VALET_REGISTRATION_UPDATE = "PROFILE_VALET_REGISTRATION_UPDATE"
    PROFILE_CUSTOMER_REGISTRATION_UPDATE = "PROFILE_CUSTOMER_REGISTRATION_UPDATE"
    PROFILE_VALET_NORMAL_UPDATE = "PROFILE_VALET_NORMAL_UPDATE"
    PROFILE_CUSTOMER_NORMAL_UPDATE = "PROFILE_CUSTOMER_NORMAL_UPDATE"


    # BOOKING Cancellation
    BOOKING_CANCELLED_BY_SUPER_ADMIN = "SUPER_ADMIN"
    BOOKING_CANCELLED_BY_ADMIN = "ADMIN"
    BOOKING_CANCELLED_BY_CUSTOMER = "CUSTOMER"
    BOOKING_CANCELLED_BY_VALET = "VALET"
    BOOKING_CANCELLED_BY_SYSTEM = "SYSTEM"

    # Booking Status
    BOOKING_STATUS_COMPLETED = "COMPLETED"
    BOOKING_STATUS_ONGOING_TRIP = "ONGOING_TRIP"
    BOOKING_STATUS_CANCELLED = "CANCELLED"
    BOOKING_STATUS_NOT_STARTED = "NOT_STARTED"


    BLANK_LIST = []
    YES = "YES"
    NO = "NO"

    DATABASE_INSERT = "INSERT"
    DATABASE_UPDATE = "UPDATE"

    MASTER_ADMIN_EMAIL = "ezeecorporation@gmail.com"
    MASTER_ADMIN_PASS = "TMM@ezeeDrop#111"
